language: generic

sudo: required

services:
  - docker

install:
  - docker build -t genprog .

# push stable builds to DockerHub
after_success:
  - if [ "${TRAVIS_BRANCH}" == "master" ]; then
      docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}";
      docker push squareslab/genprog
    fi
